default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gsan_cadastro_api_development
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: gsan_cadastro_api_test
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['GSAN_CADASTRO_DATABASE_URL'] %>
