default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>
  username: <%= ENV['DB_TEST_USER'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>
  host:     <%= ENV['DB_TEST_HOST'] %>

stage:
  <<: *default
  url: <%= ENV['GSAN_CADASTRO_DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['GSAN_CADASTRO_DATABASE_URL'] %>
